// Code generated by entc, DO NOT EDIT.

package laptop

const (
	// Label holds the string label denoting the laptop type in the database.
	Label = "laptop"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBrand holds the string denoting the brand field in the database.
	FieldBrand = "brand"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldCPU holds the string denoting the cpu field in the database.
	FieldCPU = "cpu"
	// FieldRAM holds the string denoting the ram field in the database.
	FieldRAM = "ram"
	// FieldHarddisk holds the string denoting the harddisk field in the database.
	FieldHarddisk = "harddisk"
	// Table holds the table name of the laptop in the database.
	Table = "tbl_laptop"
)

// Columns holds all SQL columns for laptop fields.
var Columns = []string{
	FieldID,
	FieldBrand,
	FieldModel,
	FieldCPU,
	FieldRAM,
	FieldHarddisk,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BrandValidator is a validator for the "brand" field. It is called by the builders before save.
	BrandValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// CPUValidator is a validator for the "cpu" field. It is called by the builders before save.
	CPUValidator func(string) error
	// RAMValidator is a validator for the "ram" field. It is called by the builders before save.
	RAMValidator func(string) error
)
