// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TblLaptopColumns holds the columns for the "tbl_laptop" table.
	TblLaptopColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "brand", Type: field.TypeString, Size: 2147483647},
		{Name: "model", Type: field.TypeString, Size: 2147483647},
		{Name: "cpu", Type: field.TypeString, Size: 2147483647},
		{Name: "ram", Type: field.TypeString, Size: 2147483647},
		{Name: "harddisk", Type: field.TypeString, Size: 2147483647},
	}
	// TblLaptopTable holds the schema information for the "tbl_laptop" table.
	TblLaptopTable = &schema.Table{
		Name:       "tbl_laptop",
		Columns:    TblLaptopColumns,
		PrimaryKey: []*schema.Column{TblLaptopColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TblLaptopTable,
	}
)

func init() {
	TblLaptopTable.Annotation = &entsql.Annotation{
		Table: "tbl_laptop",
	}
}
