// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"entsample2/ent/migrate"

	"entsample2/ent/laptop"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Laptop is the client for interacting with the Laptop builders.
	Laptop *LaptopClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Laptop = NewLaptopClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Laptop: NewLaptopClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Laptop: NewLaptopClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Laptop.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Laptop.Use(hooks...)
}

// LaptopClient is a client for the Laptop schema.
type LaptopClient struct {
	config
}

// NewLaptopClient returns a client for the Laptop from the given config.
func NewLaptopClient(c config) *LaptopClient {
	return &LaptopClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `laptop.Hooks(f(g(h())))`.
func (c *LaptopClient) Use(hooks ...Hook) {
	c.hooks.Laptop = append(c.hooks.Laptop, hooks...)
}

// Create returns a create builder for Laptop.
func (c *LaptopClient) Create() *LaptopCreate {
	mutation := newLaptopMutation(c.config, OpCreate)
	return &LaptopCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Laptop entities.
func (c *LaptopClient) CreateBulk(builders ...*LaptopCreate) *LaptopCreateBulk {
	return &LaptopCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Laptop.
func (c *LaptopClient) Update() *LaptopUpdate {
	mutation := newLaptopMutation(c.config, OpUpdate)
	return &LaptopUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LaptopClient) UpdateOne(l *Laptop) *LaptopUpdateOne {
	mutation := newLaptopMutation(c.config, OpUpdateOne, withLaptop(l))
	return &LaptopUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LaptopClient) UpdateOneID(id int) *LaptopUpdateOne {
	mutation := newLaptopMutation(c.config, OpUpdateOne, withLaptopID(id))
	return &LaptopUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Laptop.
func (c *LaptopClient) Delete() *LaptopDelete {
	mutation := newLaptopMutation(c.config, OpDelete)
	return &LaptopDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *LaptopClient) DeleteOne(l *Laptop) *LaptopDeleteOne {
	return c.DeleteOneID(l.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *LaptopClient) DeleteOneID(id int) *LaptopDeleteOne {
	builder := c.Delete().Where(laptop.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LaptopDeleteOne{builder}
}

// Query returns a query builder for Laptop.
func (c *LaptopClient) Query() *LaptopQuery {
	return &LaptopQuery{
		config: c.config,
	}
}

// Get returns a Laptop entity by its id.
func (c *LaptopClient) Get(ctx context.Context, id int) (*Laptop, error) {
	return c.Query().Where(laptop.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LaptopClient) GetX(ctx context.Context, id int) *Laptop {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LaptopClient) Hooks() []Hook {
	return c.hooks.Laptop
}
