// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"entsample2/ent/laptop"
	"entsample2/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LaptopUpdate is the builder for updating Laptop entities.
type LaptopUpdate struct {
	config
	hooks    []Hook
	mutation *LaptopMutation
}

// Where appends a list predicates to the LaptopUpdate builder.
func (lu *LaptopUpdate) Where(ps ...predicate.Laptop) *LaptopUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetBrand sets the "brand" field.
func (lu *LaptopUpdate) SetBrand(s string) *LaptopUpdate {
	lu.mutation.SetBrand(s)
	return lu
}

// SetModel sets the "model" field.
func (lu *LaptopUpdate) SetModel(s string) *LaptopUpdate {
	lu.mutation.SetModel(s)
	return lu
}

// SetCPU sets the "cpu" field.
func (lu *LaptopUpdate) SetCPU(s string) *LaptopUpdate {
	lu.mutation.SetCPU(s)
	return lu
}

// SetRAM sets the "ram" field.
func (lu *LaptopUpdate) SetRAM(s string) *LaptopUpdate {
	lu.mutation.SetRAM(s)
	return lu
}

// SetHarddisk sets the "harddisk" field.
func (lu *LaptopUpdate) SetHarddisk(s string) *LaptopUpdate {
	lu.mutation.SetHarddisk(s)
	return lu
}

// Mutation returns the LaptopMutation object of the builder.
func (lu *LaptopUpdate) Mutation() *LaptopMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LaptopUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lu.hooks) == 0 {
		if err = lu.check(); err != nil {
			return 0, err
		}
		affected, err = lu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LaptopMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lu.check(); err != nil {
				return 0, err
			}
			lu.mutation = mutation
			affected, err = lu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lu.hooks) - 1; i >= 0; i-- {
			if lu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LaptopUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LaptopUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LaptopUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LaptopUpdate) check() error {
	if v, ok := lu.mutation.Brand(); ok {
		if err := laptop.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf("ent: validator failed for field \"brand\": %w", err)}
		}
	}
	if v, ok := lu.mutation.Model(); ok {
		if err := laptop.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf("ent: validator failed for field \"model\": %w", err)}
		}
	}
	if v, ok := lu.mutation.CPU(); ok {
		if err := laptop.CPUValidator(v); err != nil {
			return &ValidationError{Name: "cpu", err: fmt.Errorf("ent: validator failed for field \"cpu\": %w", err)}
		}
	}
	if v, ok := lu.mutation.RAM(); ok {
		if err := laptop.RAMValidator(v); err != nil {
			return &ValidationError{Name: "ram", err: fmt.Errorf("ent: validator failed for field \"ram\": %w", err)}
		}
	}
	return nil
}

func (lu *LaptopUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   laptop.Table,
			Columns: laptop.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: laptop.FieldID,
			},
		},
	}
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Brand(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldBrand,
		})
	}
	if value, ok := lu.mutation.Model(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldModel,
		})
	}
	if value, ok := lu.mutation.CPU(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldCPU,
		})
	}
	if value, ok := lu.mutation.RAM(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldRAM,
		})
	}
	if value, ok := lu.mutation.Harddisk(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldHarddisk,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{laptop.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// LaptopUpdateOne is the builder for updating a single Laptop entity.
type LaptopUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LaptopMutation
}

// SetBrand sets the "brand" field.
func (luo *LaptopUpdateOne) SetBrand(s string) *LaptopUpdateOne {
	luo.mutation.SetBrand(s)
	return luo
}

// SetModel sets the "model" field.
func (luo *LaptopUpdateOne) SetModel(s string) *LaptopUpdateOne {
	luo.mutation.SetModel(s)
	return luo
}

// SetCPU sets the "cpu" field.
func (luo *LaptopUpdateOne) SetCPU(s string) *LaptopUpdateOne {
	luo.mutation.SetCPU(s)
	return luo
}

// SetRAM sets the "ram" field.
func (luo *LaptopUpdateOne) SetRAM(s string) *LaptopUpdateOne {
	luo.mutation.SetRAM(s)
	return luo
}

// SetHarddisk sets the "harddisk" field.
func (luo *LaptopUpdateOne) SetHarddisk(s string) *LaptopUpdateOne {
	luo.mutation.SetHarddisk(s)
	return luo
}

// Mutation returns the LaptopMutation object of the builder.
func (luo *LaptopUpdateOne) Mutation() *LaptopMutation {
	return luo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LaptopUpdateOne) Select(field string, fields ...string) *LaptopUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Laptop entity.
func (luo *LaptopUpdateOne) Save(ctx context.Context) (*Laptop, error) {
	var (
		err  error
		node *Laptop
	)
	if len(luo.hooks) == 0 {
		if err = luo.check(); err != nil {
			return nil, err
		}
		node, err = luo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LaptopMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = luo.check(); err != nil {
				return nil, err
			}
			luo.mutation = mutation
			node, err = luo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(luo.hooks) - 1; i >= 0; i-- {
			if luo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = luo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, luo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LaptopUpdateOne) SaveX(ctx context.Context) *Laptop {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LaptopUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LaptopUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LaptopUpdateOne) check() error {
	if v, ok := luo.mutation.Brand(); ok {
		if err := laptop.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf("ent: validator failed for field \"brand\": %w", err)}
		}
	}
	if v, ok := luo.mutation.Model(); ok {
		if err := laptop.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf("ent: validator failed for field \"model\": %w", err)}
		}
	}
	if v, ok := luo.mutation.CPU(); ok {
		if err := laptop.CPUValidator(v); err != nil {
			return &ValidationError{Name: "cpu", err: fmt.Errorf("ent: validator failed for field \"cpu\": %w", err)}
		}
	}
	if v, ok := luo.mutation.RAM(); ok {
		if err := laptop.RAMValidator(v); err != nil {
			return &ValidationError{Name: "ram", err: fmt.Errorf("ent: validator failed for field \"ram\": %w", err)}
		}
	}
	return nil
}

func (luo *LaptopUpdateOne) sqlSave(ctx context.Context) (_node *Laptop, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   laptop.Table,
			Columns: laptop.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: laptop.FieldID,
			},
		},
	}
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Laptop.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, laptop.FieldID)
		for _, f := range fields {
			if !laptop.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != laptop.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Brand(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldBrand,
		})
	}
	if value, ok := luo.mutation.Model(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldModel,
		})
	}
	if value, ok := luo.mutation.CPU(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldCPU,
		})
	}
	if value, ok := luo.mutation.RAM(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldRAM,
		})
	}
	if value, ok := luo.mutation.Harddisk(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: laptop.FieldHarddisk,
		})
	}
	_node = &Laptop{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{laptop.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
